# Configuration for Anomaly Detection Analysis

# Data configuration
data:
  real_dataset_path: 'ADNIMERGE_23Jun2024.csv'
  min_visits_required: 3
  visit_months: [0, 6, 12, 18, 24, 36, 48, 60]

# Real dataset column mapping and parsing rules
real_data:
  patient_id_col: 'RID'
  visit_code_col: 'VISCODE'
  visit_month_col: 'Month'
  exam_date_col: 'EXAMDATE'
  mmse_col: 'MMSE'
  faq_col: 'FAQ'
  age_col: 'AGE'
  gender_col: 'PTGENDER'
  education_col: 'PTEDUCAT'
  apoe4_col: 'APOE4'
  diagnosis_col: 'DX'
  baseline_dx_col: 'DX_bl'
  allowed_diagnoses: []
  gender_mapping:
    Male: 'Male'
    Female: 'Female'
    '': 'Unknown'
  max_month: 60
  month_rounding: 6
  drop_duplicates_strategy: 'best_available'
  extra_feature_columns:
    - 'ADAS13'
    - 'ADAS11'
    - 'MOCA'
  
# Feature engineering
features:
  interpolation_method: 'linear'
  max_missing_rate: 0.3
  standardize: true
  pca_variance_threshold: 0.9
  
# Isolation Forest parameters
isolation_forest:
  contamination: 0.08
  n_estimators: 512
  max_samples: 'auto'
  random_state: 42
  n_jobs: -1
  
# DBSCAN parameters
dbscan:
  eps_range: [0.5, 2.5]
  min_samples_range: [3, 8]
  metric: 'euclidean'
  
# Visualization
visualization:
  figure_size: [12, 8]
  dpi: 300
  style: 'seaborn-v0_8'
  color_palette: 'viridis'
  
# Cross-validation
cross_validation:
  n_splits: 5
  test_months: [12, 18, 24]
  validation_method: 'temporal'
  
# Output
output:
  save_plots: true
  save_results: true
  results_format: ['csv', 'json']